### ISSUE TITLE
Write the Book! (Master Ticket)

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/MoFo-Engineering-Handbook#2]
- [ ] WebSec #9
- [ ] Mobile first #15
- [ ] Front-end Monitoring, instrumentation & Metrics - Adam
- [ ] Webmaker Dev environment #5 
- [ ] Quality Assurance with People #10
- [ ] Automated Testing - #8 Atul
- [ ] Pre-flight checklist #4
- [ ] Code Reviews #7 - Atul
- [ ] Framework choices #16
- [ ] How we build content sites #8
- [ ] How we do Localization - Scott #11 
- [ ] Offline - Ali #19 
- [ ] Writing Software for Expensive and Low-bandwidth Users #14
- [ ] User Testing #6
- [ ] How we use Github Issues - Simon
- [ ] Our JavaScript Style Guide #13
